# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileOperation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='filesimplemodel',
            name='file_field',
            field=models.FileField(upload_to='D:\\DJPro\\File\\FileOperation\\static/download'),
        ),
    ]
